/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlcf_nerf;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.*;
import java.sql.Connection;

/**
 *
 * @author Admin
 */
public class MainWindoww extends javax.swing.JFrame {

    /**
     * Creates new form MainWindoww
     */
    private CardLayout cl;
    private Color maincolor = Color.decode("#C4A484");
    private Color btncolor = Color.decode("#edd5ca");
    private Color btnentercolor = Color.decode("#ECECEC");
    private int btnindexselected=0;
    private Connection c;
    
    public MainWindoww() {
        initComponents();
        functions f = new functions();
        c = f.connectDB();
        load(); 
    }
    public void load(){
        btn_home.setBackground(btncolor);
        cl = new CardLayout();
        usercontrol.setLayout(cl);
        usercontrol.add(new Panel_TrangChu(), "Trang chu");
        usercontrol.add(new Panel_BanHang(c, lbl_username.getText()), "Ban hang");
        usercontrol.add(new Panel_QLTU(), "QLTU");
        usercontrol.add(new Panel_QLNV(), "QLNV");
        usercontrol.add(new Panel_DatBan(), "Dat ban");
        usercontrol.add(new Panel_ThongKe(), "Thong ke");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainwindow = new javax.swing.JPanel();
        nav = new javax.swing.JPanel();
        p_title = new javax.swing.JPanel();
        appname = new javax.swing.JLabel();
        p_menu = new javax.swing.JPanel();
        btn_home = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_banhang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_datban = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_qlnv = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_qltu = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btn_thongke = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btn_information = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        usercontrol = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        lbl_header = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        btn_signout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Coffee shop management");
        setMinimumSize(new java.awt.Dimension(1300, 780));
        setPreferredSize(new java.awt.Dimension(1300, 780));

        mainwindow.setBackground(new java.awt.Color(196, 164, 132));

        nav.setBackground(new java.awt.Color(255, 255, 255));

        p_title.setBackground(new java.awt.Color(255, 255, 255));

        appname.setBackground(new java.awt.Color(255, 255, 255));
        appname.setFont(new java.awt.Font("Inter", 0, 22)); // NOI18N
        appname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coffee_3054889.png"))); // NOI18N
        appname.setText("<html><body>Coffee shop management</body></html>");
        appname.setIconTextGap(20);

        javax.swing.GroupLayout p_titleLayout = new javax.swing.GroupLayout(p_title);
        p_title.setLayout(p_titleLayout);
        p_titleLayout.setHorizontalGroup(
            p_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_titleLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(appname, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        p_titleLayout.setVerticalGroup(
            p_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_titleLayout.createSequentialGroup()
                .addComponent(appname, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        p_menu.setBackground(new java.awt.Color(255, 255, 255));

        btn_home.setBackground(new java.awt.Color(255, 255, 255));
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_homeMouseExited(evt);
            }
        });
        btn_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_1946488.png"))); // NOI18N
        jLabel2.setText("Trang chủ");
        jLabel2.setIconTextGap(20);
        btn_home.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, 44));

        btn_banhang.setBackground(new java.awt.Color(255, 255, 255));
        btn_banhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_banhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_banhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_banhangMouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/money-bag_550713.png"))); // NOI18N
        jLabel3.setText("Bán hàng");
        jLabel3.setIconTextGap(20);

        javax.swing.GroupLayout btn_banhangLayout = new javax.swing.GroupLayout(btn_banhang);
        btn_banhang.setLayout(btn_banhangLayout);
        btn_banhangLayout.setHorizontalGroup(
            btn_banhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_banhangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_banhangLayout.setVerticalGroup(
            btn_banhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btn_datban.setBackground(new java.awt.Color(255, 255, 255));
        btn_datban.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_datbanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_datbanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_datbanMouseExited(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar_833593.png"))); // NOI18N
        jLabel4.setText("Đặt bàn");
        jLabel4.setIconTextGap(20);

        javax.swing.GroupLayout btn_datbanLayout = new javax.swing.GroupLayout(btn_datban);
        btn_datban.setLayout(btn_datbanLayout);
        btn_datbanLayout.setHorizontalGroup(
            btn_datbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_datbanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_datbanLayout.setVerticalGroup(
            btn_datbanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btn_qlnv.setBackground(new java.awt.Color(255, 255, 255));
        btn_qlnv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_qlnvMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_qlnvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_qlnvMouseExited(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/assessment.png"))); // NOI18N
        jLabel5.setText("Quản lý nhân viên");
        jLabel5.setIconTextGap(20);

        javax.swing.GroupLayout btn_qlnvLayout = new javax.swing.GroupLayout(btn_qlnv);
        btn_qlnv.setLayout(btn_qlnvLayout);
        btn_qlnvLayout.setHorizontalGroup(
            btn_qlnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_qlnvLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_qlnvLayout.setVerticalGroup(
            btn_qlnvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btn_qltu.setBackground(new java.awt.Color(255, 255, 255));
        btn_qltu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_qltuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_qltuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_qltuMouseExited(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coffee.png"))); // NOI18N
        jLabel6.setText("Quản lý thức uống");
        jLabel6.setIconTextGap(20);

        javax.swing.GroupLayout btn_qltuLayout = new javax.swing.GroupLayout(btn_qltu);
        btn_qltu.setLayout(btn_qltuLayout);
        btn_qltuLayout.setHorizontalGroup(
            btn_qltuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_qltuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
        );
        btn_qltuLayout.setVerticalGroup(
            btn_qltuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        btn_thongke.setBackground(new java.awt.Color(255, 255, 255));
        btn_thongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_thongkeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_thongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_thongkeMouseExited(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bar-chart.png"))); // NOI18N
        jLabel7.setText("Thống kê");
        jLabel7.setIconTextGap(20);

        javax.swing.GroupLayout btn_thongkeLayout = new javax.swing.GroupLayout(btn_thongke);
        btn_thongke.setLayout(btn_thongkeLayout);
        btn_thongkeLayout.setHorizontalGroup(
            btn_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_thongkeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_thongkeLayout.setVerticalGroup(
            btn_thongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout p_menuLayout = new javax.swing.GroupLayout(p_menu);
        p_menu.setLayout(p_menuLayout);
        p_menuLayout.setHorizontalGroup(
            p_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_menuLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(p_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_banhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_datban, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_qlnv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_qltu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_thongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        p_menuLayout.setVerticalGroup(
            p_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_menuLayout.createSequentialGroup()
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btn_banhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btn_datban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btn_qlnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btn_qltu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btn_thongke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btn_information.setBackground(new java.awt.Color(255, 255, 255));
        btn_information.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel8.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information.png"))); // NOI18N
        jLabel8.setText("Thông tin về app");
        jLabel8.setIconTextGap(20);

        javax.swing.GroupLayout btn_informationLayout = new javax.swing.GroupLayout(btn_information);
        btn_information.setLayout(btn_informationLayout);
        btn_informationLayout.setHorizontalGroup(
            btn_informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_informationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_informationLayout.setVerticalGroup(
            btn_informationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_informationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout navLayout = new javax.swing.GroupLayout(nav);
        nav.setLayout(navLayout);
        navLayout.setHorizontalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_information, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        navLayout.setVerticalGroup(
            navLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(p_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(p_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addComponent(btn_information, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout usercontrolLayout = new javax.swing.GroupLayout(usercontrol);
        usercontrol.setLayout(usercontrolLayout);
        usercontrolLayout.setHorizontalGroup(
            usercontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        usercontrolLayout.setVerticalGroup(
            usercontrolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        header.setBackground(new java.awt.Color(255, 255, 255));

        lbl_header.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        lbl_header.setText("jLabel4");

        lbl_username.setFont(new java.awt.Font("Inter", 0, 20)); // NOI18N
        lbl_username.setText("Username");

        btn_signout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_header)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 724, Short.MAX_VALUE)
                .addComponent(lbl_username)
                .addGap(18, 18, 18)
                .addComponent(btn_signout)
                .addGap(30, 30, 30))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_header)
                        .addComponent(lbl_username))
                    .addComponent(btn_signout))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout mainwindowLayout = new javax.swing.GroupLayout(mainwindow);
        mainwindow.setLayout(mainwindowLayout);
        mainwindowLayout.setHorizontalGroup(
            mainwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainwindowLayout.createSequentialGroup()
                .addComponent(nav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainwindowLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(mainwindowLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usercontrol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainwindowLayout.setVerticalGroup(
            mainwindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainwindowLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usercontrol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainwindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainwindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        // TODO add your handling code here:
        btn_home.setBackground(btncolor);
        btnindexselected = 0;
        
        btn_banhang.setBackground(Color.WHITE);;
        btn_datban.setBackground(Color.WHITE);
        btn_qlnv.setBackground(Color.WHITE);
        btn_qltu.setBackground(Color.WHITE);
        btn_thongke.setBackground(Color.WHITE);
        
        lbl_header.setText("Trang chủ");
        cl.show(usercontrol, "Trang chu");
    }//GEN-LAST:event_btn_homeMouseClicked

    private void btn_thongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_thongkeMouseClicked
        // TODO add your handling code here:
        btn_thongke.setBackground(btncolor);
        btnindexselected = 5;
        
        btn_banhang.setBackground(Color.WHITE);
        btn_datban.setBackground(Color.WHITE);
        btn_qlnv.setBackground(Color.WHITE);
        btn_qltu.setBackground(Color.WHITE);
        btn_home.setBackground(Color.WHITE);
        
        lbl_header.setText("Thống kê doanh thu");
        cl.show(usercontrol, "Thong ke");
    }//GEN-LAST:event_btn_thongkeMouseClicked

    private void btn_qltuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_qltuMouseClicked
        // TODO add your handling code here:
        btn_qltu.setBackground(btncolor);
        btnindexselected = 4;
        
        btn_banhang.setBackground(Color.WHITE);
        btn_datban.setBackground(Color.WHITE);
        btn_qlnv.setBackground(Color.WHITE);
        btn_home.setBackground(Color.WHITE);
        btn_thongke.setBackground(Color.WHITE);
        
        lbl_header.setText("Quản lý thức uống");
        cl.show(usercontrol, "QLTU");
    }//GEN-LAST:event_btn_qltuMouseClicked

    private void btn_qlnvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_qlnvMouseClicked
        // TODO add your handling code here:
        btn_qlnv.setBackground(btncolor);
        btnindexselected = 3;
        
        btn_banhang.setBackground(Color.WHITE);
        btn_datban.setBackground(Color.WHITE);
        btn_home.setBackground(Color.WHITE);
        btn_qltu.setBackground(Color.WHITE);
        btn_thongke.setBackground(Color.WHITE);
        
        lbl_header.setText("Quản lý nhân viên");
        cl.show(usercontrol, "QLNV");
    }//GEN-LAST:event_btn_qlnvMouseClicked

    private void btn_datbanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_datbanMouseClicked
        // TODO add your handling code here:
        btn_datban.setBackground(btncolor);
        btnindexselected = 2;
        
        btn_banhang.setBackground(Color.WHITE);
        btn_home.setBackground(Color.WHITE);
        btn_qlnv.setBackground(Color.WHITE);
        btn_qltu.setBackground(Color.WHITE);
        btn_thongke.setBackground(Color.WHITE);
        
        lbl_header.setText("Đặt bàn");
        cl.show(usercontrol, "Dat ban");
    }//GEN-LAST:event_btn_datbanMouseClicked

    private void btn_banhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_banhangMouseClicked
        // TODO add your handling code here:
        btn_banhang.setBackground(btncolor);
        btnindexselected = 1;
        
        btn_home.setBackground(Color.WHITE);
        btn_datban.setBackground(Color.WHITE);
        btn_qlnv.setBackground(Color.WHITE);
        btn_qltu.setBackground(Color.WHITE);
        btn_thongke.setBackground(Color.WHITE);
        
        lbl_header.setText("Bán hàng");
        cl.show(usercontrol, "Ban hang");
    }//GEN-LAST:event_btn_banhangMouseClicked

    private void btn_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseEntered
        // TODO add your handling code here:
        if(btnindexselected != 0){
            btn_home.setBackground(btnentercolor);
        } 
    }//GEN-LAST:event_btn_homeMouseEntered

    private void btn_banhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_banhangMouseEntered
        // TODO add your handling code here:
        if(btnindexselected != 1){
            btn_banhang.setBackground(btnentercolor);
        } 
    }//GEN-LAST:event_btn_banhangMouseEntered

    private void btn_datbanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_datbanMouseEntered
        // TODO add your handling code here:
        if(btnindexselected != 2){
            btn_datban.setBackground(btnentercolor);
        } 
    }//GEN-LAST:event_btn_datbanMouseEntered

    private void btn_qlnvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_qlnvMouseEntered
        // TODO add your handling code here:
        if(btnindexselected != 3){
            btn_qlnv.setBackground(btnentercolor);
        } 
    }//GEN-LAST:event_btn_qlnvMouseEntered

    private void btn_qltuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_qltuMouseEntered
        // TODO add your handling code here:
        if(btnindexselected != 4){
            btn_qltu.setBackground(btnentercolor);
        } 
    }//GEN-LAST:event_btn_qltuMouseEntered

    private void btn_thongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_thongkeMouseEntered
        // TODO add your handling code here:
        if(btnindexselected != 5){
            btn_thongke.setBackground(btnentercolor);
        } 
    }//GEN-LAST:event_btn_thongkeMouseEntered

    private void btn_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseExited
        // TODO add your handling code here:
        if(btnindexselected != 0){
            btn_home.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_btn_homeMouseExited

    private void btn_banhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_banhangMouseExited
        // TODO add your handling code here:
        if(btnindexselected != 1){
            btn_banhang.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_btn_banhangMouseExited

    private void btn_datbanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_datbanMouseExited
        // TODO add your handling code here:
        if(btnindexselected != 2){
            btn_datban.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_btn_datbanMouseExited

    private void btn_qlnvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_qlnvMouseExited
        // TODO add your handling code here:
        if(btnindexselected != 3){
            btn_qlnv.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_btn_qlnvMouseExited

    private void btn_qltuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_qltuMouseExited
        // TODO add your handling code here:
        if(btnindexselected != 4){
            btn_qltu.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_btn_qltuMouseExited

    private void btn_thongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_thongkeMouseExited
        // TODO add your handling code here:
        if(btnindexselected != 5){
            btn_thongke.setBackground(Color.WHITE);
        }
    }//GEN-LAST:event_btn_thongkeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindoww.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindoww.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindoww.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindoww.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindoww().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appname;
    private javax.swing.JPanel btn_banhang;
    private javax.swing.JPanel btn_datban;
    private javax.swing.JPanel btn_home;
    private javax.swing.JPanel btn_information;
    private javax.swing.JPanel btn_qlnv;
    private javax.swing.JPanel btn_qltu;
    private javax.swing.JLabel btn_signout;
    private javax.swing.JPanel btn_thongke;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbl_header;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPanel mainwindow;
    private javax.swing.JPanel nav;
    private javax.swing.JPanel p_menu;
    private javax.swing.JPanel p_title;
    private javax.swing.JPanel usercontrol;
    // End of variables declaration//GEN-END:variables
}
