/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package qlcf_nerf;

import java.sql.*;
import javax.swing.table.*;
import java.util.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class Panel_QLNV extends javax.swing.JPanel {

    private String gender;
    private Connection c;
    private PreparedStatement pst;
    private ResultSet rs;
    /**
     * Creates new form QLNV_Panel
     */
    public Panel_QLNV() {
        initComponents();
        functions f = new functions();
        c = f.connectDB();
        showQLNV();
    }
    
    /**
     * This method is called from within the coConnection constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // custom functions
    private void showQLNV(){
        String query="SELECT NHANVIEN.*, ACCOUNT.TAIKHOAN, ACCOUNT.MATKHAU FROM NHANVIEN JOIN ACCOUNT ON NHANVIEN.MANV = ACCOUNT.MANV";
        try{
            pst=c.prepareStatement(query);
            rs=pst.executeQuery();
            ResultSetMetaData rsmd=rs.getMetaData();
            int n = rsmd.getColumnCount();
            String[] colName = new String[n];
            for (int i = 0; i<n;i++){
                colName[i] = rsmd.getColumnName(i+1);
            }
            DefaultTableModel dfm= (DefaultTableModel)tbl_nv.getModel();
            dfm.setRowCount(0);
            dfm.setColumnIdentifiers(colName);
            while(rs.next()){
                Vector v=new Vector();
                for(int i=1;i<=n;i++){
                    v.add(rs.getString("MANV"));
                    v.add(rs.getString("HOTEN"));
                    v.add(rs.getString("GIOITINH"));
                    v.add(rs.getString("NGAYSINH"));
                    v.add(rs.getString("SDT"));
                    v.add(rs.getString("DIACHI"));
                    v.add(rs.getString("TAIKHOAN"));
                    v.add(rs.getString("MATKHAU"));
                }
                dfm.addRow(v);
            }
        }
        catch(SQLException e){
            e.printStackTrace();
        }
    }
    private static boolean isNumeric(String str) {
        return str.matches("\\d+");
    }
    
    private boolean checkNull(){
        if(tf_manv.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mã nhân viên!");
            return false;
        }
        else
        if(tf_hoten.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập họ tên!");
            return false;
        }
        else
        if(tf_ngaysinh.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập ngày sinh!");
            return false;
        }
        else   
        if(!rad_nam.isSelected() && !rad_nu.isSelected()){
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn giới tính!");
            return false;
        }
        else   
        if(tf_sdt.getText().equals("") || !isNumeric(tf_sdt.getText())){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập số điện thoại hoặc nhập sai định dạng!");
            return false;
        }
        else  
        if(tf_diachi.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập địa chỉ!");
            return false;
        }
        else
        if(tf_taikhoan.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập tài khoản!");
            return false;
        }
        else
        if(tf_matkhau.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập mật khẩu!");
            return false;
        }
        return true;
    }
    private void themNV(){
        if (checkNull()){
            String employeeId = tf_manv.getText();
            if (kiemTraTonTaiNhanVien(employeeId)) {
                JOptionPane.showMessageDialog(null, "Nhân viên với mã " + employeeId + " đã tồn tại. Không thể thêm mới.");
                return;
            }
            
            String q2 = "INSERT INTO ACCOUNT VALUES('"+ tf_taikhoan.getText() +"', '" + tf_matkhau.getText() + "', '"+ tf_manv.getText() + "', \'Nhan vien\')";
            String q1 = "INSERT INTO NHANVIEN VALUES('"+tf_manv.getText()+"', '"+ tf_hoten.getText()+"', '"+gender+"', '"+ tf_ngaysinh.getText()+"', '"+tf_sdt.getText()+"', '"+tf_diachi.getText()+"')";
            try{
                pst = c.prepareStatement(q1);
                pst.executeUpdate();
                pst = c.prepareStatement(q2);
                pst.executeUpdate();
                showQLNV();
                JOptionPane.showMessageDialog(null, "Thêm nhân viên thành công!");
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }
    private boolean kiemTraTonTaiNhanVien(String employeeId) {
        String query = "SELECT COUNT(*) FROM NHANVIEN WHERE MANV = ?";
        try {
            pst = c.prepareStatement(query);
            pst.setString(1, employeeId);
            ResultSet resultSet = pst.executeQuery();
            resultSet.next();
            int rowCount = resultSet.getInt(1);
            return rowCount > 0;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            return false;
        }
    }   
    private void xoaNV(){
        int option = JOptionPane.showConfirmDialog(null,"Bạn có chắc chắn muốn xoá?", "Xoá", 2);
        if (option == JOptionPane.YES_OPTION){
            String q = "DELETE FROM NHANVIEN WHERE MANV='" + tf_manv.getText() + "'";
            try{
                pst = c.prepareStatement(q);
                pst.executeUpdate();
                showQLNV();
                JOptionPane.showMessageDialog(null, "Xoá nhân viên thành công!");
            }
            catch(SQLException e){
                e.printStackTrace();
            }
        }
    }
    private void suaNV(){
        if (checkNull()){
            String q1 = "UPDATE NHANVIEN SET HOTEN='" + tf_hoten.getText() +"', GIOITINH='" + gender + "', NGAYSINH='" + tf_ngaysinh.getText() +"', SDT='" + tf_sdt.getText() +"', DIACHI='"+ tf_diachi.getText() + "' WHERE MANV='"+ tf_manv.getText()+"'" ;
            String q2 = "UPDATE ACCOUNT SET TAIKHOAN='" + tf_taikhoan.getText() +"', MATKHAU='" + tf_matkhau.getText() +"' WHERE MANV='" + tf_manv.getText() +"'";
            try{
                pst = c.prepareStatement(q1);
                pst.executeUpdate();
                pst = c.prepareStatement(q2);
                pst.executeUpdate();
                showQLNV();
                JOptionPane.showMessageDialog(null, "Sửa nhân viên thành công!");
            }
            catch(SQLException e){
                e.printStackTrace();
            }
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tf_manv = new javax.swing.JTextField();
        tf_hoten = new javax.swing.JTextField();
        tf_ngaysinh = new javax.swing.JFormattedTextField();
        rad_nam = new javax.swing.JRadioButton();
        rad_nu = new javax.swing.JRadioButton();
        tf_sdt = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        tf_diachi = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        tf_taikhoan = new javax.swing.JTextField();
        tf_matkhau = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_nv = new javax.swing.JTable();

        setBackground(new java.awt.Color(196, 164, 132));
        setMinimumSize(new java.awt.Dimension(970, 650));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(970, 650));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel22.setText("Thông tin nhân viên");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel23.setText("Mã nhân viên:");

        jLabel24.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel24.setText("Họ và tên:");

        jLabel25.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel25.setText("Ngày sinh:");

        jLabel26.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel26.setText("Giới tính:");

        tf_manv.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        tf_manv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_manvActionPerformed(evt);
            }
        });

        tf_hoten.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N

        tf_ngaysinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tf_ngaysinh.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        tf_ngaysinh.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N

        buttonGroup1.add(rad_nam);
        rad_nam.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        rad_nam.setText("Nam");
        rad_nam.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rad_namStateChanged(evt);
            }
        });
        rad_nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rad_namActionPerformed(evt);
            }
        });

        buttonGroup1.add(rad_nu);
        rad_nu.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        rad_nu.setText("Nữ");

        tf_sdt.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel27.setText("Số điện thoại:");

        tf_diachi.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel28.setText("Địa chỉ:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(rad_nam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                                .addComponent(rad_nu))
                            .addComponent(tf_ngaysinh)
                            .addComponent(tf_sdt)
                            .addComponent(tf_diachi)
                            .addComponent(tf_hoten)
                            .addComponent(tf_manv))))
                .addGap(21, 21, 21))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_manv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(rad_nam)
                    .addComponent(rad_nu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tf_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(tf_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jLabel29.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel29.setText("Tài khoản:");

        jLabel30.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        jLabel30.setText("Mật khẩu:");

        tf_taikhoan.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N

        tf_matkhau.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        btn_them.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        jPanel10.add(btn_them);

        btn_xoa.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        btn_xoa.setText("Xoá");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        jPanel10.add(btn_xoa);

        btn_sua.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel10.add(btn_sua);

        btn_reset.setFont(new java.awt.Font("Inter", 0, 16)); // NOI18N
        btn_reset.setText("Xoá các mục đã nhập");
        jPanel10.add(btn_reset);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_matkhau, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(tf_taikhoan))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(12, 12, 12)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        jLabel35.setFont(new java.awt.Font("Inter", 1, 18)); // NOI18N
        jLabel35.setText("Danh sách nhân viên của quán:");

        tbl_nv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_nv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_nvMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbl_nv);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tf_manvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_manvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_manvActionPerformed

    private void rad_namStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rad_namStateChanged
        // TODO add your handling code here:
        if (rad_nam.isSelected()) gender="Nam";
        else gender="Nu";
    }//GEN-LAST:event_rad_namStateChanged

    private void rad_namActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rad_namActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rad_namActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        themNV();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        suaNV();
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        xoaNV();
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void tbl_nvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_nvMouseClicked
        // TODO add your handling code here:
        int id_selected = tbl_nv.getSelectedRow();
        TableModel model = tbl_nv.getModel();
        tf_manv.setText(model.getValueAt(id_selected, 0).toString());
        tf_hoten.setText(model.getValueAt(id_selected, 1).toString());
        if(model.getValueAt(id_selected, 2).toString().equals("Nam")) {
            rad_nam.setSelected(true);
            gender="Nam";
        }
        else {
            rad_nu.setSelected(true);
            gender="Nu";
        }
        tf_ngaysinh.setText(model.getValueAt(id_selected, 3).toString());
        tf_sdt.setText(model.getValueAt(id_selected, 4).toString());
        tf_diachi.setText(model.getValueAt(id_selected, 5).toString());
        tf_taikhoan.setText(model.getValueAt(id_selected, 6).toString());
        tf_matkhau.setText(model.getValueAt(id_selected, 7).toString());
    }//GEN-LAST:event_tbl_nvMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JRadioButton rad_nam;
    private javax.swing.JRadioButton rad_nu;
    private javax.swing.JTable tbl_nv;
    private javax.swing.JTextField tf_diachi;
    private javax.swing.JTextField tf_hoten;
    private javax.swing.JTextField tf_manv;
    private javax.swing.JTextField tf_matkhau;
    private javax.swing.JFormattedTextField tf_ngaysinh;
    private javax.swing.JTextField tf_sdt;
    private javax.swing.JTextField tf_taikhoan;
    // End of variables declaration//GEN-END:variables
}
